# Generated by Django 5.0.4 on 2024-05-12 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
