# Generated by Django 5.0.7 on 2024-08-15 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_restaurant_reviews_restaurant_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurantreview',
            old_name='ambiance_rating',
            new_name='rating',
        ),
        migrations.RemoveField(
            model_name='restaurantreview',
            name='food_quality_rating',
        ),
        migrations.RemoveField(
            model_name='restaurantreview',
            name='service_rating',
        ),
        migrations.AddField(
            model_name='restaurantreview',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
