# Generated by Django 5.0.7 on 2024-08-15 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_rename_ambiance_rating_restaurantreview_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantreview',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='restaurantreview',
            name='restaurant_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
